version: "3.7"
services:
  backend:
    build: ./
    ports:
      - 8080:8080
    restart: always
    environment:
      MYSQL_HOST: db
    networks:
      - spring-mysql
    depends_on:
      db:
        condition: service_healthy
  db:
    environment:
      MYSQL_DATABASE: example
      MYSQL_ROOT_PASSWORD: root
    image: mysql:latest
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    networks:
      - spring-mysql
networks:
  spring-mysql: {}
